-- 在 Oracle 数据库中，空字符串和 NULL 是等价的

DROP TABLE EM_FLOW_DEFINITION;
DROP TABLE EM_FLOW_DEPLOYMENT;
DROP TABLE EI_FLOW_INSTANCE;
DROP TABLE EI_FLOW_INSTANCE_MAPPING;
DROP TABLE EI_NODE_INSTANCE;
DROP TABLE EI_NODE_INSTANCE_LOG;
DROP TABLE EI_INSTANCE_DATA;

DROP SEQUENCE SEQ_EM_FLOW_DEFINITION;
DROP SEQUENCE SEQ_EM_FLOW_DEPLOYMENT;
DROP SEQUENCE SEQ_EI_FLOW_INSTANCE;
DROP SEQUENCE SEQ_EI_FLOW_INSTANCE_MAPPING;
DROP SEQUENCE SEQ_EI_NODE_INSTANCE;
DROP SEQUENCE SEQ_EI_NODE_INSTANCE_LOG;
DROP SEQUENCE SEQ_EI_INSTANCE_DATA;

CREATE TABLE EM_FLOW_DEFINITION
(
    ID             NUMBER(19)                                                                         NOT NULL
        CONSTRAINT PK_FLOW_DEFINITION PRIMARY KEY,
    FLOW_MODULE_ID VARCHAR2(128),
    FLOW_NAME      VARCHAR2(64),
    FLOW_KEY       VARCHAR2(32),
    TENANT_ID      VARCHAR2(16),
    FLOW_MODEL     CLOB,
    STATUS         NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    CREATE_TIME    TIMESTAMP     DEFAULT SYSTIMESTAMP                                                 NOT NULL,
    MODIFY_TIME    TIMESTAMP     DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    OPERATOR       VARCHAR2(32),
    REMARK         VARCHAR2(512),
    ARCHIVE        NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    TENANT         VARCHAR2(100),
    CALLER         VARCHAR2(100)
);

CREATE UNIQUE INDEX UNIQ_FLOW_MODULE_ID ON EM_FLOW_DEFINITION (FLOW_MODULE_ID);


CREATE SEQUENCE SEQ_EM_FLOW_DEFINITION START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EM_FLOW_DEFINITION BEFORE INSERT ON EM_FLOW_DEFINITION FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EM_FLOW_DEFINITION.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EM_FLOW_DEFINITION IS '流程定义表';
COMMENT ON COLUMN EM_FLOW_DEFINITION.ID             IS '自增主键';
COMMENT ON COLUMN EM_FLOW_DEFINITION.FLOW_MODULE_ID IS '流程模型id';
COMMENT ON COLUMN EM_FLOW_DEFINITION.FLOW_NAME      IS '流程名称';
COMMENT ON COLUMN EM_FLOW_DEFINITION.FLOW_KEY       IS '流程业务标识';
COMMENT ON COLUMN EM_FLOW_DEFINITION.TENANT_ID      IS '业务方标识';
COMMENT ON COLUMN EM_FLOW_DEFINITION.FLOW_MODEL     IS '表单定义';
COMMENT ON COLUMN EM_FLOW_DEFINITION.STATUS         IS '状态(1.初始态 2.编辑中 3.已下线)';
COMMENT ON COLUMN EM_FLOW_DEFINITION.CREATE_TIME    IS '流程创建时间';
COMMENT ON COLUMN EM_FLOW_DEFINITION.MODIFY_TIME    IS '流程修改时间';
COMMENT ON COLUMN EM_FLOW_DEFINITION.OPERATOR       IS '操作人';
COMMENT ON COLUMN EM_FLOW_DEFINITION.REMARK         IS '备注';
COMMENT ON COLUMN EM_FLOW_DEFINITION.ARCHIVE        IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EM_FLOW_DEFINITION.TENANT         IS '租户';
COMMENT ON COLUMN EM_FLOW_DEFINITION.CALLER         IS '调用方';


CREATE TABLE EM_FLOW_DEPLOYMENT
(
    ID             NUMBER(19)                                                                         NOT NULL
        CONSTRAINT PK_FLOW_DEPLOYMENT PRIMARY KEY,
    FLOW_DEPLOY_ID VARCHAR2(128),
    FLOW_MODULE_ID VARCHAR2(128),
    FLOW_NAME      VARCHAR2(64),
    FLOW_KEY       VARCHAR2(32),
    TENANT_ID      VARCHAR2(16),
    FLOW_MODEL     CLOB,
    STATUS         NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    CREATE_TIME    TIMESTAMP     DEFAULT SYSTIMESTAMP                                                 NOT NULL,
    MODIFY_TIME    TIMESTAMP     DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    OPERATOR       VARCHAR2(32),
    REMARK         VARCHAR2(512),
    ARCHIVE        NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    TENANT         VARCHAR2(100),
    CALLER         VARCHAR2(100)
);

CREATE UNIQUE INDEX UNIQ_FLOW_DEPLOY_ID ON EM_FLOW_DEPLOYMENT (FLOW_DEPLOY_ID);
CREATE INDEX IDX_FLOW_MODULE_ID ON EM_FLOW_DEPLOYMENT (FLOW_MODULE_ID);

CREATE SEQUENCE SEQ_EM_FLOW_DEPLOYMENT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EM_FLOW_DEPLOYMENT BEFORE INSERT ON EM_FLOW_DEPLOYMENT FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EM_FLOW_DEPLOYMENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EM_FLOW_DEPLOYMENT IS '流程部署表';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.ID             IS '自增主键';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.FLOW_DEPLOY_ID IS '流程模型部署id';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.FLOW_MODULE_ID IS '流程模型id';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.FLOW_NAME      IS '流程名称';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.FLOW_KEY       IS '流程业务标识';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.TENANT_ID      IS '业务方标识';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.FLOW_MODEL     IS '表单定义';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.STATUS         IS '状态(1.已部署 3.已下线)';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.CREATE_TIME    IS '流程创建时间';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.MODIFY_TIME    IS '流程修改时间';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.OPERATOR       IS '操作人';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.REMARK         IS '备注';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.ARCHIVE        IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.TENANT         IS '租户';
COMMENT ON COLUMN EM_FLOW_DEPLOYMENT.CALLER         IS '调用方';


CREATE TABLE EI_FLOW_INSTANCE
(
    ID                      NUMBER(19)                                                                         NOT NULL
        CONSTRAINT PK_FLOW_INSTANCE PRIMARY KEY,
    FLOW_INSTANCE_ID        VARCHAR2(128),
    PARENT_FLOW_INSTANCE_ID VARCHAR2(128),
    FLOW_DEPLOY_ID          VARCHAR2(128),
    FLOW_MODULE_ID          VARCHAR2(128),
    TENANT_ID               VARCHAR2(16),
    STATUS                  NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    CREATE_TIME             TIMESTAMP     DEFAULT SYSTIMESTAMP                                                 NOT NULL,
    MODIFY_TIME             TIMESTAMP     DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    ARCHIVE                 NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    TENANT                  VARCHAR2(100),
    CALLER                  VARCHAR2(100)
);

CREATE UNIQUE INDEX UNIQ_FLOW_INSTANCE_ID ON EI_FLOW_INSTANCE (FLOW_INSTANCE_ID);


CREATE SEQUENCE SEQ_EI_FLOW_INSTANCE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EI_FLOW_INSTANCE BEFORE INSERT ON EI_FLOW_INSTANCE FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EI_FLOW_INSTANCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EI_FLOW_INSTANCE IS '流程执行实例表';
COMMENT ON COLUMN EI_FLOW_INSTANCE.ID                      IS '自增主键';
COMMENT ON COLUMN EI_FLOW_INSTANCE.FLOW_INSTANCE_ID        IS '流程执行实例id';
COMMENT ON COLUMN EI_FLOW_INSTANCE.PARENT_FLOW_INSTANCE_ID IS '父流程执行实例id';
COMMENT ON COLUMN EI_FLOW_INSTANCE.FLOW_DEPLOY_ID          IS '流程模型部署id';
COMMENT ON COLUMN EI_FLOW_INSTANCE.FLOW_MODULE_ID          IS '流程模型id';
COMMENT ON COLUMN EI_FLOW_INSTANCE.TENANT_ID               IS '业务方标识';
COMMENT ON COLUMN EI_FLOW_INSTANCE.STATUS                  IS '状态(1.执行完成 2.执行中 3.执行终止(强制终止))';
COMMENT ON COLUMN EI_FLOW_INSTANCE.CREATE_TIME             IS '流程创建时间';
COMMENT ON COLUMN EI_FLOW_INSTANCE.MODIFY_TIME             IS '流程修改时间';
COMMENT ON COLUMN EI_FLOW_INSTANCE.ARCHIVE                 IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EI_FLOW_INSTANCE.TENANT                  IS '租户';
COMMENT ON COLUMN EI_FLOW_INSTANCE.CALLER                  IS '调用方';


CREATE TABLE EI_FLOW_INSTANCE_MAPPING
(
    ID                   NUMBER(19)                                                                         NOT NULL
        CONSTRAINT PK_FLOW_INSTANCE_MAPPING PRIMARY KEY,
    FLOW_INSTANCE_ID     VARCHAR2(128),
    NODE_INSTANCE_ID     VARCHAR2(128),
    NODE_KEY             VARCHAR2(64),
    SUB_FLOW_INSTANCE_ID VARCHAR2(128),
    TYPE                 NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    CREATE_TIME          TIMESTAMP     DEFAULT SYSTIMESTAMP                                                 NOT NULL,
    MODIFY_TIME          TIMESTAMP     DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    ARCHIVE              NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    TENANT               VARCHAR2(100),
    CALLER               VARCHAR2(100)
);

CREATE INDEX IDX_FII ON EI_FLOW_INSTANCE_MAPPING (FLOW_INSTANCE_ID);
CREATE SEQUENCE SEQ_EI_FLOW_INSTANCE_MAPPING START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EI_FLOW_INSTANCE_MAPPING BEFORE INSERT ON EI_FLOW_INSTANCE_MAPPING FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EI_FLOW_INSTANCE_MAPPING.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EI_FLOW_INSTANCE IS '父子流程实例映射表';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.ID                   IS '自增主键';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.FLOW_INSTANCE_ID     IS '流程执行实例id';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.NODE_INSTANCE_ID     IS '节点执行实例id';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.NODE_KEY             IS '节点唯一标识';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.SUB_FLOW_INSTANCE_ID IS '子流程执行实例id';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.TYPE                 IS '状态(1.执行 2.回滚)';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.CREATE_TIME          IS '流程创建时间';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.MODIFY_TIME          IS '流程修改时间';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.ARCHIVE              IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.TENANT               IS '租户';
COMMENT ON COLUMN EI_FLOW_INSTANCE_MAPPING.CALLER               IS '调用方';


CREATE TABLE EI_NODE_INSTANCE
(
    ID                      NUMBER(19)                                                                         NOT NULL
        CONSTRAINT PK_NODE_INSTANCE PRIMARY KEY,
    NODE_INSTANCE_ID        VARCHAR2(128),
    FLOW_INSTANCE_ID        VARCHAR2(128),
    SOURCE_NODE_INSTANCE_ID VARCHAR2(128),
    INSTANCE_DATA_ID        VARCHAR2(128),
    FLOW_DEPLOY_ID          VARCHAR2(128),
    NODE_KEY                VARCHAR2(64),
    SOURCE_NODE_KEY         VARCHAR2(64),
    TENANT_ID               VARCHAR2(16),
    STATUS                  NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    CREATE_TIME             TIMESTAMP     DEFAULT SYSTIMESTAMP                                                 NOT NULL,
    MODIFY_TIME             TIMESTAMP     DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    ARCHIVE                 NUMBER(4)     DEFAULT 0                                                            NOT NULL,
    TENANT                  VARCHAR2(100),
    CALLER                  VARCHAR2(100)
);

CREATE UNIQUE INDEX UNIQ_NODE_INSTANCE_ID ON EI_NODE_INSTANCE (NODE_INSTANCE_ID);
CREATE INDEX IDX_FIID_SNIID_NK ON EI_NODE_INSTANCE (FLOW_INSTANCE_ID, SOURCE_NODE_INSTANCE_ID, NODE_KEY);

CREATE SEQUENCE SEQ_EI_NODE_INSTANCE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EI_NODE_INSTANCE BEFORE INSERT ON EI_NODE_INSTANCE FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EI_NODE_INSTANCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EI_FLOW_INSTANCE IS '节点执行实例表';
COMMENT ON COLUMN EI_NODE_INSTANCE.ID                      IS '自增主键';
COMMENT ON COLUMN EI_NODE_INSTANCE.NODE_INSTANCE_ID        IS '节点执行实例id';
COMMENT ON COLUMN EI_NODE_INSTANCE.FLOW_INSTANCE_ID        IS '流程执行实例id';
COMMENT ON COLUMN EI_NODE_INSTANCE.SOURCE_NODE_INSTANCE_ID IS '上一个节点执行实例id';
COMMENT ON COLUMN EI_NODE_INSTANCE.INSTANCE_DATA_ID        IS '实例数据id';
COMMENT ON COLUMN EI_NODE_INSTANCE.FLOW_DEPLOY_ID          IS '流程模型部署id';
COMMENT ON COLUMN EI_NODE_INSTANCE.NODE_KEY                IS '节点唯一标识';
COMMENT ON COLUMN EI_NODE_INSTANCE.SOURCE_NODE_KEY         IS '上一个流程节点唯一标识';
COMMENT ON COLUMN EI_NODE_INSTANCE.TENANT_ID               IS '业务方标识';
COMMENT ON COLUMN EI_NODE_INSTANCE.STATUS                  IS '状态(1.处理成功 2.处理中 3.处理失败 4.处理已撤销)';
COMMENT ON COLUMN EI_NODE_INSTANCE.CREATE_TIME             IS '流程创建时间';
COMMENT ON COLUMN EI_NODE_INSTANCE.MODIFY_TIME             IS '流程修改时间';
COMMENT ON COLUMN EI_NODE_INSTANCE.ARCHIVE                 IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EI_NODE_INSTANCE.TENANT                  IS '租户';
COMMENT ON COLUMN EI_NODE_INSTANCE.CALLER                  IS '调用方';



CREATE TABLE EI_NODE_INSTANCE_LOG
(
    ID               NUMBER(19)                         NOT NULL
        CONSTRAINT PK_NODE_INSTANCE_LOG PRIMARY KEY,
    NODE_INSTANCE_ID VARCHAR2(128),
    FLOW_INSTANCE_ID VARCHAR2(128),
    INSTANCE_DATA_ID VARCHAR2(128),
    NODE_KEY         VARCHAR2(64),
    TENANT_ID        VARCHAR2(16),
    TYPE             NUMBER(4)     DEFAULT 0            NOT NULL,
    STATUS           NUMBER(4)     DEFAULT 0            NOT NULL,
    CREATE_TIME      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ARCHIVE          NUMBER(4)     DEFAULT 0            NOT NULL,
    TENANT           VARCHAR2(100),
    CALLER           VARCHAR2(100)
);

CREATE SEQUENCE SEQ_EI_NODE_INSTANCE_LOG START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EI_NODE_INSTANCE_LOG BEFORE INSERT ON EI_NODE_INSTANCE_LOG FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EI_NODE_INSTANCE_LOG.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EI_NODE_INSTANCE_LOG IS '节点执行记录表';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.ID                IS '自增主键';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.NODE_INSTANCE_ID  IS '节点执行实例id';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.FLOW_INSTANCE_ID  IS '流程执行实例id';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.INSTANCE_DATA_ID  IS '实例数据id';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.NODE_KEY          IS '节点唯一标识';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.TENANT_ID         IS '业务方标识';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.TYPE              IS '操作类型(1.系统执行 2.任务提交 3.任务撤销)';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.STATUS            IS '状态(1.处理成功 2.处理中 3.处理失败 4.处理已撤销)';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.CREATE_TIME       IS '流程创建时间';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.ARCHIVE           IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.TENANT            IS '租户';
COMMENT ON COLUMN EI_NODE_INSTANCE_LOG.CALLER            IS '调用方';



CREATE TABLE EI_INSTANCE_DATA
(
    ID               NUMBER(19)                         NOT NULL
        CONSTRAINT PK_INSTANCE_DATA PRIMARY KEY,
    NODE_INSTANCE_ID VARCHAR2(128),
    FLOW_INSTANCE_ID VARCHAR2(128),
    INSTANCE_DATA_ID VARCHAR2(128),
    FLOW_DEPLOY_ID   VARCHAR2(128),
    FLOW_MODULE_ID   VARCHAR2(128),
    NODE_KEY         VARCHAR2(64),
    TENANT_ID        VARCHAR2(16),
    INSTANCE_DATA    CLOB,
    TYPE             NUMBER(4)     DEFAULT 0            NOT NULL,
    CREATE_TIME      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    ARCHIVE          NUMBER(4)     DEFAULT 0            NOT NULL,
    TENANT           VARCHAR2(100),
    CALLER           VARCHAR2(100)
);

CREATE UNIQUE INDEX UNIQ_INSTANCE_DATA_ID ON EI_INSTANCE_DATA (INSTANCE_DATA_ID);
CREATE INDEX IDX_FLOW_INSTANCE_ID ON EI_INSTANCE_DATA (FLOW_INSTANCE_ID);

CREATE SEQUENCE SEQ_EI_INSTANCE_DATA START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRIGGER_EI_INSTANCE_DATA BEFORE INSERT ON EI_INSTANCE_DATA FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EI_INSTANCE_DATA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMENT ON TABLE EI_INSTANCE_DATA IS '实例数据表';
COMMENT ON COLUMN EI_INSTANCE_DATA.ID               IS '自增主键';
COMMENT ON COLUMN EI_INSTANCE_DATA.NODE_INSTANCE_ID IS '节点执行实例id';
COMMENT ON COLUMN EI_INSTANCE_DATA.FLOW_INSTANCE_ID IS '流程执行实例id';
COMMENT ON COLUMN EI_INSTANCE_DATA.INSTANCE_DATA_ID IS '实例数据id';
COMMENT ON COLUMN EI_INSTANCE_DATA.FLOW_DEPLOY_ID   IS '流程模型部署id';
COMMENT ON COLUMN EI_INSTANCE_DATA.FLOW_MODULE_ID   IS '流程模型id';
COMMENT ON COLUMN EI_INSTANCE_DATA.NODE_KEY         IS '节点唯一标识';
COMMENT ON COLUMN EI_INSTANCE_DATA.TENANT_ID        IS '业务方标识';
COMMENT ON COLUMN EI_INSTANCE_DATA.INSTANCE_DATA    IS '数据列表json';
COMMENT ON COLUMN EI_INSTANCE_DATA.TYPE             IS '操作类型(1.实例初始化 2.系统执行 3.系统主动获取 4.上游更新 5.任务提交 6.任务撤回)';
COMMENT ON COLUMN EI_INSTANCE_DATA.CREATE_TIME      IS '流程创建时间';
COMMENT ON COLUMN EI_INSTANCE_DATA.ARCHIVE          IS '归档状态(0未删除，1删除)';
COMMENT ON COLUMN EI_INSTANCE_DATA.TENANT           IS '租户';
COMMENT ON COLUMN EI_INSTANCE_DATA.CALLER           IS '调用方';
